### ISSUE TITLE
Can't connect to mongodb

### ISSUE THREAD

**Issue by cmwint** [seppevs/migrate-mongo#11]
I'm having a very hard time connecting to mongo. It's locally on my computer and I've tried both localhost and 127.0.0.1 for the URL but nothing is working. However, I keep getting a 'failed to connect to server' error.

Do I need something else to connect? Do I need mongoose somewhere? I appreciate any help that points me in the right direction. Thank you.

**Comment by cmwint** [comment]
Figured it out. Sorry, I jumped the gun on asking for help. Thanks for a great tool!

**Comment by seppevs** [comment]
You're welcome!
