### ISSUE TITLE
Error: final argument to `executeOperation` must be a callback

### ISSUE THREAD

**Issue by cmwint** [seppevs/migrate-mongo#12]
This is the migration I wrote: 

```
'use strict';

module.exports = {

  up(db, next) {
    db.collection('projects')
    .updateMany({}, { $set: { tags: [] }}, false, true)
    .then(next);
  },

  down(db, next) {
    db.collection('projects')
    .updateMany({}, { $unset: { tags: [] }}, false, true)
    .then(next);
  }

};
```

Very simple and I am following the directions exactly. But when I run the up command, I keep getting an error that says: 
`ERROR: Could not migrate up 20180406191421-add_project_tags.js: final argument to 'executeOperation' must be a callback`

What is going wrong here? Any help is appreciated. Thank you.

**Comment by seppevs** [comment]
When using Promises, you must return the Promise:

Example:
````javascript
'use strict';

module.exports = {

  up(db) {
    return db.collection('projects')
    .updateMany({}, { $set: { tags: [] }}, false, true);
  },

  down(db) {
    return db.collection('projects')
    .updateMany({}, { $unset: { tags: [] }}, false, true);
  }

};
````
You do not have to use the `next` callback in this case.

**Comment by cmwint** [comment]
Oh, thank you so much. This helped a lot. I promise this is the last silly issue I will open on your repo!

**Comment by seppevs** [comment]
No problem, I'm glad to help :)

**Comment by emjerez** [comment]
Hi @seppevs!

I seem to be having this same issue. 

This is my migration file:

'use strict';

module.exports = {
  up(db) {
    return db.collection('campaign')
    .updateMany({ customerId: { $exists: false } }, {$set: {"customerId": '9999999'}}, false, true);
  },

  down(db) {
    return db.collection('campaign')
    .updateMany({ customerId: { $exists: true } }, {$unset: {"customerId": '9999999'}}, false, true);
  }
};

ERROR: Could not migrate up 20190122160457-campaign_add_new_fields.js: final argument to `executeOperation` must be a callback

Any help would be great, thank you!!

**Comment by seppevs** [comment]
`.updateMany({ customerId: { $exists: false } }, {$set: {"customerId": '9999999'}}, false, true);`

Why are you passing those 2 last boolean parameters?
See [the docs of updateMany](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#updateMany)

Options = the 3rd parameter 
Callback = the 4th parameter

Try to leave out `false, true` in your call
