### ISSUE TITLE
Setting order/dependencies of migrations

### ISSUE THREAD

**Issue by jole78** [seppevs/migrate-mongo#123]
I use migrate mongo both for migrations and for seeding test data into mongo. Some seeds/migrations rely on the fact that other seeds/migrations have been applied beforehand.

So my question/request is that if there either is some built-in way that I haven't considered or if a seed/migration can rely/depend on another seed/migration being executed before another migration tries to execute.

This would of course work in environments where we only add new migrations but we quite often run this locally to clean/setup the environment and then they are all new/pending.

I know that for example django (on the python stack) has this built in to their migrations framework that otherwise work very similar to this project.

Thanks! // Johan

**Comment by seppevs** [comment]
Each time a new migration is created, migrate-mongo will append a timestamp to the migration file.
This timestamp is used to determine the order in which the `up` action will execute all pending migrations.

Does this answer your question?

**Comment by jole78** [comment]
I know it works like that yes...meaning that each new migration (or seed in my case) is basically appended to the list (so to say). My question was generally if there was a possibility to have migrations depend on each other (if one was to have multiple migration folders or something).
But I guess I'll close the question since I guess currently there's no such possibility in scope...
