### ISSUE TITLE
TypeError when no migration is left 

### ISSUE THREAD

**Issue by gruberb** [seppevs/migrate-mongo#15]
I want to run `migrate-mongo up` on every deployment. But I found out when there are no more `scripts` left to run, it blows up:

```
/usr/local/opt/backend/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: undefined is not a function
    at Function.apply (/usr/local/opt/backend/node_modules/shifting/index.js:93:11)
```

I also get the same `TypeError` after applying a migration.

**Comment by seppevs** [comment]
I cannot reproduce this. Can you try to create an example project?

**Comment by gruberb** [comment]
Sorry, my bad. I changed the folder structure to:
```
migrations/
     {date}-name.js
     {date}-name.js
     config.js
```

And inside config, I set `migrationsDir:  '.',`

But then it tries to run `config.js` as a migration.

**Comment by gruberb** [comment]
Btw, great module! Do you need help converting it to ES6 or other tasks?

**Comment by seppevs** [comment]
Thanks! No, it can already work with Promises (and thus async & await as well), I don't mind it still uses callbacks internally :)
