### ISSUE TITLE
config.js fallback name/path

### ISSUE THREAD

**Issue by AlexLibs** [seppevs/migrate-mongo#17]
I want to use `migrate-mongo` in my project.

In my project all the system configuration is managed with very popular [config](https://www.npmjs.com/package/config) package. It allows to manage configuration per environment. Of course I want to manage there also `migrate-mongo` configuration. In this case my `migrate-mongo` configuration file `config.js` will be:

```
'use strict';
const config = require('config');

module.exports = config.get('migrations'); 
```

1. `config` package looks for configuration files in `./config` directory.
2. `migrate-mongo` package expects configuration file `config.js` in the current directory.

So:
1. If I run `migrate-mongo` commands from my project's root directory I will have to put `migrate-mongo` configuration file `config.js` in my project's root directory (and `config.js` has too general name to be there).

2. If I put `migrate-mongo` configuration file `config.js` in any inner directory (e.g. `./migrations/`)  then I have to run `migrate-mongo` commands from there and then `config` package will not find its configuration files, unless I put a copy of its config directory under migration directory which is obviously wrong.

I would like it to try to use `config.js` from the current path (for backward compatibility) and if there is no such a file as fallback to check for example `.\migrations\config.js` or event just another name (e.g. `migrations_config.js`). I would prefer the first option (e.g. `.\migrations\config.js` ), to keep my project's root directory as clean as possible.

**Comment by seppevs** [comment]
Maybe this can help you? https://github.com/seppevs/migrate-mongo/blob/master/README.md#using-a-custom-config-file

Remember, the `config.js` is just a javascript file, so it can contain conditions (or even use `require` statements) to resolve your migrate-mongo configuration.

**Comment by seppevs** [comment]
I'm closing this.
