### ISSUE TITLE
be able to organize migrations scripts in sub-level directory structure

### ISSUE THREAD

**Issue by kaiso** [seppevs/migrate-mongo#18]
Presently migrate-mongo reads only files under the "migrationDir" config value, it would be helpfull to be able to organize migrations files in subdirectories like version for example with the following layout:

`

       |____ v1.0.0
       |        |____  213233-script.js
       |____ v1.1.0
                |___ ... other scripts
`

**Comment by seppevs** [comment]
Sorry, I won't add this. It would make the code more complex without any direct benefit.
