### ISSUE TITLE
Do not allow to migrate downwards all the ran migrations.

### ISSUE THREAD

**Issue by farhantahir** [seppevs/migrate-mongo#19]
Its a great package and we are using it in our production but I found an issue with this package. Currently if you run `migrate-mongo down` even after days it downgrades the previously ran migrations.

How I thought it would work was as follow:

`migrate-mongo up` runs the new migrations and keeps track of latest ran migrations.Then if I do `migrate-mongo down` it only downgrades the previously ran migrations.

Later if I do `migrate-mongo down` again, (in my case I did accidentally). It should not downgrade the next migration available instead should show message `No migrations ran`.

What I'm saying is this package should `cache` the recently ran migration and only should downgrade the these.This way even doing `migrate-mongo down` after days won't create data discrepancies. 

If you think this should be fixed I would love to work on this :stuck_out_tongue:

**Comment by jacksonStone** [comment]
@farhantahir this would lead to really unexpected results in the event of a dev swapping between issue branches. Even if they ran the migration several days ago.

**Comment by seppevs** [comment]
Yes, it works as designed. I'm closing this.
