### ISSUE TITLE
default to more specific config path

### ISSUE THREAD

**Issue by willshowell** [seppevs/migrate-mongo#22]
First, thank you for such a helpful project!

This was pointed out in https://github.com/seppevs/migrate-mongo/issues/3 and https://github.com/seppevs/migrate-mongo/issues/17, but I think it's pretty important: `config.js` is a very generic name.

The project I'm including this package in has 10 third-party config files in the root directory and that's not including internal ones. It doesn't make sense that `config.js` is reserved for just a single (though important!) portion of the application.

I realize we can use the `--file` flag, but it would be far more convenient if migrate-mongoose would first look for a more specific config (e.g. `migrations_config.js`, `mm-config.js`, `.migrationrc.js`, etc).

I suspect this would be as simple as changing how `DEFAULT_CONFIG_FILE_NAME` is checked, and would easily be made backward compatible as long as the new name is pretty unique. I'm also happy to contribute if you're cool with this approach.

**Comment by seppevs** [comment]
Fixed in v4.0.0 🎉
The new default config file is `migrate-mongo-config.js`

**Comment by willshowell** [comment]
Thank you for your work on this! 😄
