### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by rafalskyi** [seppevs/migrate-mongo#23]
cannot use import syntax in config file

`/config.js:1
(function (exports, require, module, __filename, __dirname) { import { mongo } from '../src/config'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
`

**Comment by seppevs** [comment]
You need to use `require` (commonJS) instead of `import` and `export` (ECMAScript modules).

**Comment by rafalskyi** [comment]
@seppevs do you plan to support "import"?

**Comment by seppevs** [comment]
It's not something I have to support. It depends on the Node.js runtime you use.
Whenever ECMAScript modules have landed in Node, you should be able to use the `import` syntax.
[Check this](https://nodejs.org/api/esm.html)
