### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by stherrienaspnet** [seppevs/migrate-mongo#25]
When execution migration on the following script I'm getting this message. That seems strange since I'm using insertMany as recommended, do you see something wrong in my script?  The collection does not exist before this command.

  up(db, next) {
      db.collection('physical-type')
          .insertMany([
          {physicalTypeCode: 10, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'Seconds' ,supportDifferential: true},
          {physicalTypeCode: 12, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'°C' ,supportDifferential: true}
      ]);
    next();
  },

DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.

Thanks

**Comment by seppevs** [comment]
Not sure it's related (I haven't tried to reproduce your issue). But I did spot an error in your code:

```javascript
up(db, next) {
	db.collection('physical-type')
	.insertMany([
		{physicalTypeCode: 10, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'Seconds' ,supportDifferential: true},
		{physicalTypeCode: 12, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'°C' ,supportDifferential: true}
	]);
	next();
},
```

You need to pass the callback `next` as the second argument:

```javascript
up(db, next) {
	db.collection('physical-type')
	.insertMany([
		{physicalTypeCode: 10, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'Seconds' ,supportDifferential: true},
		{physicalTypeCode: 12, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'°C' ,supportDifferential: true}
	], next);
},
```

Or use the Promise feature:

```javascript
up(db) {
	return db.collection('physical-type')
	.insertMany([
		{physicalTypeCode: 10, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'Seconds' ,supportDifferential: true},
		{physicalTypeCode: 12, minLimit: -3.4E+38, maxLimit: 3.4E+38, dbDataUnit:'°C' ,supportDifferential: true}
	]);
},
```

Does that help you?

**Comment by stherrienaspnet** [comment]
all the code blocks are giving the same results.  For your first block where I pass next as last parameter, I i have several collections to update do I add next only to the last one command?

**Comment by stherrienaspnet** [comment]
Also I wandering what would be the easiest way to you directory for our scripts, like sprint1, sprint2?

**Comment by stherrienaspnet** [comment]
![image](https://user-images.githubusercontent.com/6126961/45561158-0dca8400-b815-11e8-96ad-b10c89a57ffb.png)

**Comment by stherrienaspnet** [comment]
I found a solution for using a script for directory structure, only thing remaining is the strange warning :)

**Comment by joelmukuthu** [comment]
Hi @stherrienaspnet, since your code doesn’t actually call `collection.insert` I’m guessing it might be in some other migration file, which might then be hidden by the fact that some async operations are not being awaited.

I’d recommend using promises and await all the db calls in your migrations: `await collection.insertMany(items)`. More: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by stherrienaspnet** [comment]
Thanks Joel! I will give a try with await :)

**Comment by stherrienaspnet** [comment]
I finally found the issue, I removed a unused type dependency as follow 
npm remove @types/mongodb
after no more depreciation warning message :)
