### ISSUE TITLE
DeprecationWarning shown after updating to latest version of migrate-mongo

### ISSUE THREAD

**Issue by carlos-granados** [seppevs/migrate-mongo#256]
**Describe the bug**
When `migrate-mongo` is run we get this warning: `DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

**To Reproduce**
Just run `migrate-mongo` with any option

**Expected behavior**
No deprecation warning should be thrown

**Additional context**
This happens with `migrate-mongo` 8.1.2, `mongodb` 3.6.2, node 12

**Comment by daveboulard** [comment]
Hello @carlos-granados !

Are you sure you haven't commented out the line 13 in your migrate-mongo-config.js or are running an older version of it ?
It should contain the option you are mentioning.

You can see it here : https://github.com/seppevs/migrate-mongo/blob/master/samples/migrate-mongo-config.js#L13

**Comment by seppevs** [comment]
It looks like that was the issue. I'm closing this.
