### ISSUE TITLE
DBUrl as environment variable

### ISSUE THREAD

**Issue by itaied246** [seppevs/migrate-mongo#28]
Is it possible to init the migration tool using an environment variable?

**Comment by powderham** [comment]
I also would like to be able to set the db url dynamically based on the environment. 

Is there another way for me to use one config file for both test and production?

**Comment by seppevs** [comment]
You can define your database url in an environment variable:
```bash
DBURL=mongodb://dev-server:27017
```
... and refer to this in your `migrate-mongo-config.js` file:
```javascript
module.exports = {
  mongodb: {
    url: process.env.DBURL,
    databaseName: "YOURDATABASENAME",
  },
  migrationsDir: "migrations",
  changelogCollectionName: "changelog"
};
```

This works because the `migrate-mongo-config.js` is interpreted through Node. You can even `require` other modules in there.

**Comment by heath3n** [comment]
I'm using dotenv and I just get `ERROR: No url defined in config file!`
