### ISSUE TITLE
Feature requests and PR flow

### ISSUE THREAD

**Issue by daveboulard** [seppevs/migrate-mongo#282]
Hello !

First of all, I would like to thank @seppevs and the community for the work done on this tool.
It is really helping us dealing with migrations and has enough potential for us to invest time on it.
Some PRs have been made, accepted and merged in the main branch.
Which is always a nice feeling :)

Nevertheless, some PRs are just sitting there, for some time now.
Without a single comment.
And I am wondering why.

Is it because of a lack of time to investigate ? A feeling of irrelevance on some or all of them ?
Some proposed changes not in accordance with a "future release", if any ?

Please be sure I'm not here to fuss or complain or whine.
It is more a reach to discuss, improve and understand the way a feature is requested for it to be smooth for everyone involved :)
And, ultimately, helping out if needed ;)

Again, thank you for your time and take care.

**Comment by seppevs** [comment]
It's because of a lack of time. Sorry!
