### ISSUE TITLE
Use migrationFileExtension for sample-migration

### ISSUE THREAD

**Issue by noisyscanner** [seppevs/migrate-mongo#317]
**Describe the bug**
If I set `migrationFileExtension` to `.ts` for TypeScript, I would expect it to load `sample-migration.ts` instead of `sample-migration.js`

**To Reproduce**
1. Create a sample migration file at `migrations/sample-migration.ts`
2. Set `migrationFileExtension` to `.ts` in `migrate-mongo-config.js`
3. Run `mirate-mongo create migrationName`

**Expected behavior**
Migration to be created using template at `migrations/sample-migration.ts`

**Actual behavior**
Migration not created using template - the default built-in template is used instead

**Additional context**
Another potential solution could be the abilit to specify `sampleMigrationFileName` or something in `migrate-mongo-config.js`

**Comment by seppevs** [comment]
Resolved by merging [this PR](https://github.com/seppevs/migrate-mongo/pull/280)
