### ISSUE TITLE
Is there a Support to connect to multiple database at a time?

### ISSUE THREAD

**Issue by ram6696** [seppevs/migrate-mongo#324]
I have a use case where I have to connect to 2 databases at a time and I query a table in one database and update the table with the value i got from first database in another database table

So Is there a way in migrate-mango where I can connect to both the database using mango-migrate-config file

**Comment by pkallu** [comment]
I have similar requirement. how can i connect to multiple databases?

**Comment by PedroPascoal6** [comment]
I had the same issue
If you are using a version above migrate-mongo 7.x.x. use the client parameter on up function to redefine your db

see this example 
`client.db('dbName').createCollection('sampleCollection')`

migration file:

![image](https://user-images.githubusercontent.com/20194035/114478159-91c79100-9bf5-11eb-9e36-dc4c554820f7.png)


The version restriction is [here](https://github.com/seppevs/migrate-mongo/blob/4906ff23676ba3b2a9be219be64eb94f440db597/lib/actions/up.js#L21):

**Comment by seppevs** [comment]
I suggest to run your migrate scripts twice. I will not add support for multiple databases. I want to keep this tool as simple as possible (both the code and usage).
