### ISSUE TITLE
Error requiring migration file obfuscated by library's error handling

### ISSUE THREAD

**Issue by willshowell** [seppevs/migrate-mongo#33]
**Describe the bug**

The error handler for `up` tries to log the migrations that couldn't be run. This is done in `/bin/migrate-mongo` on L72.

https://github.com/seppevs/migrate-mongo/blob/a610b9e6eb12647a02dadd0e0834b3702cc38c90/bin/migrate-mongo.js#L58-L75

But if `err.migrated` is undefined, then a new error is thrown before the original error can be logged:

```
TypeError: Cannot read property 'forEach' of undefined
    at printMigrated (node_modules/migrate-mongo/bin/migrate-mongo.js:12:12)
    at database.connect.then.then.catch.err (node_modules/migrate-mongo/bin/migrate-mongo.js:74:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Unfortunately, some errors are thrown that don't have the `migrated` property, so it's difficult to get visibility into them.

**To Reproduce**
- write a migration that throws an error when required
    ```js
    // requiring this file will error due to using await inside non-async fn
    module.exports = {
      up(db) {
        await somePromise
      }

      down(db) { }
    };
    ```
- use `migrate-mongo up`

**Other**

Also if inserting the migration to the db collection fails, then you'll get an invalid error there as well:

https://github.com/seppevs/migrate-mongo/blob/a610b9e6eb12647a02dadd0e0834b3702cc38c90/lib/actions/up.js#L35-L39

**Comment by seppevs** [comment]
Should be resolved in v4.1.2
See https://github.com/seppevs/migrate-mongo/pull/34
