### ISSUE TITLE
Inconsistent issue in pushing values to empty arrays

### ISSUE THREAD

**Issue by arketec** [seppevs/migrate-mongo#37]
**Describe the bug**
Sometimes, when running multiple $push updates on an empty array, the first $push statement is missed/skipped resulting in a single element missing from the array field

**To Reproduce**
Let's say there is a mongo collection called "sample" with an empty array field like this:
```
{_id: ObjectId('000000000000000000'), name: 'sample1', an_array_field: []}
```

Now, I want to make a migration to add some elements 
```
db.collection('sample').update({name: 'sample1'}, {$push: {an_array_field: "test val 1"}}, next)
db.collection('sample').update({name: 'sample1'}, {$push: {an_array_field: "test val 2"}}, next)
db.collection('sample').update({name: 'sample1'}, {$push: {an_array_field: "test val 3"}}, next)
```

**Expected behavior**
After running this migration, I would expect the document to looks like this:
```
{_id: ObjectId('000000000000000000'), name: 'sample1', an_array_field: ["test val 1", "test val 2", "test val 3"]}
```

However, what sometimes (inconsistently) happens is this:
```
{_id: ObjectId('000000000000000000'), name: 'sample1', an_array_field: ["test val 2", "test val 3"]}
```

Notice how the first value is missing.

**Additional context**
This only happens when the updated field is an empty array, and it does not always happen. As an example of the inconsistent behavior, lets say this worked as expected locally and on a dev server, but failed to include the first value in the production environment. Same migration script, same versions of all dependencies, even the same docker container. Only difference is the configured mongo database host and the time ran.

Further more, we have had the same script work correctly the first time, and but skip the first element the second time after rolling back and running again, then working the third time after rolling back and running again.

**Comment by seppevs** [comment]
This is not a bug. You are not using callbacks correctly.

```javascript
db.collection('sample').update({name: 'sample1'}, {$push: {an_array_field: "test val 1"}}, next)
db.collection('sample').update({name: 'sample1'}, {$push: {an_array_field: "test val 2"}}, next)
db.collection('sample').update({name: 'sample1'}, {$push: {an_array_field: "test val 3"}}, next)
```
==> you call the callback, `next` in this case, 3 times instead of 1 time.
If you use callbacks, **you must call the callback** (`next` in this case) **only once.**

There are several ways to fix it:
1. Use [async and await](https://github.com/seppevs/migrate-mongo#example-2-use-async--await).
1. Use [promises](https://github.com/seppevs/migrate-mongo#example-1-return-a-promise) instead of callbacks
2. If you really want to keep using callbacks: use a library like [async](https://caolan.github.io/async/)

I suggest option 1.

**Comment by arketec** [comment]
ok, thank you for the tip
