### ISSUE TITLE
Ability to set migration directories or use patterns

### ISSUE THREAD

**Issue by Jtosbornex** [seppevs/migrate-mongo#38]
When setting up a project with many different models it is nice to have migrations next to each model. 

Inside of the configuration, it would be great If I could use an array or regex to map to migrations directories.

The alternate approach here would be to simply have one giant migrations folder. 

Im attempting to use this inside of nestjs which is a dependency management system. It looks as though I am going to end up using migrations in a procedural way, without dependency injection.

**Comment by seppevs** [comment]
Sorry, I see not much benefit in this and I want to keep migrate-mongo simple. Closing this.
