### ISSUE TITLE
How to Unit test migration functions

### ISSUE THREAD

**Issue by rowlandekemezie** [seppevs/migrate-mongo#391]
We're currently adopting migrate-mongo as our migration tool, but we have concerns about data loss, especially with the **down** function.
Is there a standard or known way to write unit tests for the migration functions(up & down)?

**Comment by seppevs** [comment]
Some ideas:
* You can pass a mocked db in the `up` and/or `down` functions of your migration.
* You can run your migration against a test database?

I'm closing this, as it is not an issue IMHO.
