### ISSUE TITLE
`create` command misses --file option

### ISSUE THREAD

**Issue by kpk-arkuda** [seppevs/migrate-mongo#4]
`create` command requires default configuration file to be present in current root project directory. Does it really need it? How to specify custom config file for `create`? It misses `-f` option.

**Comment by seppevs** [comment]
I think you're right and I will look into it. Thank you for your input!

**Comment by seppevs** [comment]
I have just pushed a fix. Upgrade to migrate-mongo v1.2.2

**Comment by kpk-arkuda** [comment]
Thank you for instant fix!
Nice framework, we chose it out of several ones.
