### ISSUE TITLE
Database Not Updating Correctly.

### ISSUE THREAD

**Issue by bvpranu97** [seppevs/migrate-mongo#405]
I have multiple database queries to run. I have to fetch some data from db, for each data I have to do some computations and update the document fetched.  I didn't write any migration-down script, just left blank.
When I run the migrate up, the execution leaves many documents not updated. Again If I run migrate down and run migrate up again and again the documents gets updated.

The issue is that the script is not completely executing for long time it seems.

**Comment by seppevs** [comment]
Closing this, the description of this issue is too vague for me sorry.
