### ISSUE TITLE
Remove the extension from the filename, or provide an option to do so.

### ISSUE THREAD

**Issue by dphrag** [seppevs/migrate-mongo#414]
**Is your feature request related to a problem? Please describe.**
If a project uses Javascript and then later converts to Typescript, the storage of the file extension in the database for checking if a migration was run creates inconsistencies.

**Describe the solution you'd like**
There's no particular reason the extension should have been included in the stored filename IMO, however it'll be hard to remove for compatibility. Suggest adding an option to the migration config (e.g. "--ignore-extension") that ignores the extension that is stored when checking if the file was run.

**Comment by seppevs** [comment]
Sorry, won't do. I want to keep this tool as simple as possible, without too many bells and whistles.
