### ISSUE TITLE
Storing Migration results and ability to view them

### ISSUE THREAD

**Issue by NTTAKR** [seppevs/migrate-mongo#419]
Hi!

I really enjoy working with migrate-mongo. It is definitively a big time-saver. 

Most of my migration code does have some output stating how many instances were migrated, or even if migration could not be established on one or more documents. 
Currently I just use console.log to do the output. 

This would be incredibly useful if migrate-mongo would save this output in the migration table so you are able to look at it at a later time.

**Comment by seppevs** [comment]
Cool idea, but I want to keep migrate-mongo as simple as possible so I'm afraid I will not add this feature. 
You could always pipe the output of migrate-mongo to a text file? Good luck.
