### ISSUE TITLE
--dry-run option

### ISSUE THREAD

**Issue by malerba118** [seppevs/migrate-mongo#43]
**Is your feature request related to a problem? Please describe.**
When writing up and down functions I have to run migrate-mongo up and then migrate-mongo down in order to test my implementation.

**Describe the solution you'd like**
It would be nice if there was an option migrate-mongo up --dry-run that would let me test my code but wouldn't actually apply the migration.

**Comment by Stradivario** [comment]
This is called a Transaction.

The only way of doing this is with new support for ACID transactions inside MongoDB. Where you `startTransaction` and then `commit` when the transaction and all conditions are met. The only implementation at the moment for older Databases is that it `Touches` the database and simulate transaction behaviour but indeed it will mutate data and then revert it on API level. So this is not something you can deal with...

What you suggest is really cool but it depends on the situation and it is a developer choice weather to do it or not. 

This is issue is also related with https://github.com/seppevs/migrate-mongo/issues/48

**Comment by seppevs** [comment]
Sorry, I don't think this one is realistic to implement since migration scripts mutate data. Closing this.
