### ISSUE TITLE
ESM mode not compatible with migrationFileExtension in TS

### ISSUE THREAD

**Issue by RomainOliva** [seppevs/migrate-mongo#430]
**Describe the bug**

If you set ESM mode in config and migrationFileExtension: `.ts`, it didn't work and you get a 
```SyntaxError: Unexpected token 'export'```

It work well if migration file are `.js`

**To Reproduce**

set this in your config : 
```
migrationFileExtension: '.js',
moduleSystem: 'esm',
```
And create a migration with `.ts` extension

**Expected behavior**
The `migrate-mongo up` work without js error

Thanks in advance for your help :)

**Comment by seppevs** [comment]
TypeScript is not officially supported by migrate-mongo. JavaScript is sufficient to write database migration scripts IMHO. I'm closing this.
