### ISSUE TITLE
Allow passing of extra arguments

### ISSUE THREAD

**Issue by axelyung** [seppevs/migrate-mongo#44]
**Is your feature request related to a problem? Please describe.**
I really like the API of this library over other migration frameworks that support Mongoose, but I would still like to use the Mongoose library in certain situations. Furthermore, there are other operations where it would helpful if custom arguments (utilities, metadata, etc) could be passed as an extra argument in `down`/`up` scripts.

**Describe the solution you'd like**
I would like to include a user-defined extra argument in the `up`/`down` functions.

**Describe alternatives you've considered**
Possible solution:
```
module.exports = {
	up(db, extra) {
		const { mongoose, utils, meta } = extra;
		utils.logger('Updating The Beatle\'s blacklist value');
		return mongoose.Albums.updateMany({
			artist: 'The Beatles',
		}, {
			$set: {
				blacklisted: meta.defaultBlacklistValue,
			},
		});
	},
	...
```

This extra argument could be defined in the config file when using the CLI or passed as an extra argument when using the Node API:
```
// migrate-mongo-config.js
module.exports = {
	...

	extra: {
		mongoose: mongoose.connect('mongodb://localhost/music'),
		utils: {
			logger: (...msgs) => console.log(...msgs)
		},
		meta: {
			defaultBlacklistValue: false,
		}
	}
};

// node API
const mm = require('migrate-mongo');

...

mm.up(db, extra)
```

**Additional context**
n/a

**Comment by seppevs** [comment]
You can have a package.json file in your migration project directory, and install dependencies with `npm install`. You will be able to use these dependencies in your migration scripts.

You can also have other javascript files in your migration project directory, and `require` them in your migration scripts.

Does that solve your issue?

**Comment by seppevs** [comment]
Closing this.
