### ISSUE TITLE
Typescript & mongoose support

### ISSUE THREAD

**Issue by MikeKoval** [seppevs/migrate-mongo#440]
Hi!

Thank you for migrate-mongo, great tool we started using actively when we disabled autoIndex in mongoose and started changing schema actively .

I 've read https://github.com/seppevs/migrate-mongo/issues/79 and https://github.com/seppevs/migrate-mongo/issues/396

1. Why there are no plans to support ts? Have you noticed that there are forks of this project like https://github.com/mycodeself/mongo-migrate-ts that are actually I think TS is really popular and requirement for many projects and provide many benefits. In case it supported TS i think it might be even more popular. Seems there is a way to start this project with TS but there is no mention in README how to set it up properly.

```
Migration scripts, apart from collection creation and others, mainly deal with index creation and its management. Mongoose does not recommend using itself for dealing with indices.
That should be a strong enough reason not to use Mongoose.
```
2. Can you share some references to this info pls? I found only this mention https://mongoosejs.com/docs/api/model.html#Model.ensureIndexes() pointing to the fact that default autoIndex: true is bad idea.
3. Also the thing is we use this lib not only for indexes modifications but also for schema changes and actual data migrations. We really would like that all data manipulations are made using schema and its validation to avoid data issues when it does not match schema....

**Comment by seppevs** [comment]
Hi,

Sorry, but I don't think migrate-mongo should have a dependency on mongoose.
TypeScript support might be nice, but IMHO it is overkill for writing database migration scripts. I like to keep migrate-mongo as simple as possible.
