### ISSUE TITLE
Can't access the mongodb module

### ISSUE THREAD

**Issue by carlos-granados** [seppevs/migrate-mongo#45]
In my migrations I need access to other NodeJs MongoDB objects like `ObjectId` and `DBRef`

I am trying to use:
```
var ObjectID = require('mongodb').ObjectID;
var DBRef = require('mongodb').DBRef;
```

but I get
`Cannot find module 'mongodb'`

How can I access these objects?

**Comment by seppevs** [comment]
Sorry for the late reply. Can you try to add a 'package.json' file to your migrations project + add 'mongodb' as a dependency.

The `migrate-mongo` should be able to resolve the dependencies you've listed in your package.json.

**Comment by seppevs** [comment]
Closing this.
