### ISSUE TITLE
Flag -f doesn't work for the create command

### ISSUE THREAD

**Issue by a-rodin** [seppevs/migrate-mongo#6]
The flag `-f` doesn't work for the `create` command, so it throws and error if it is passed.

I think it might be more consistent to accept this flag, but ignore the config file content if it is not needed.

Usage: I defined an `npm` command aliases `npm migrate-mongo` to `npm migrate-mongo -f migrate-mongo-config.js`, so I want to use it for all commands. However it crashes for `npm migrate create` because `-f` flag doesn't work with the `create` command.

**Comment by seppevs** [comment]
Fixed in version 2.1.3
