### ISSUE TITLE
Lodash vulnerability (prototype pollution)

### ISSUE THREAD

**Issue by DanielRuf** [seppevs/migrate-mongo#66]
Might be useful to use `patch-package` or `snyk`.
I would recommend `patch-package` as solution to patch more if needed.

https://snyk.io/test/github/seppevs/migrate-mongo

https://snyk-rules-pre-repository.s3.amazonaws.com/snapshots/master/patches/npm/lodash/20190702/lodash_20190702_0_0_1f8ea07746963a535385a5befc19fa687a627d2b.patch

**Comment by seppevs** [comment]
Fixed in 6.0.1. Alle dependencies are up to date.
