### ISSUE TITLE
Working with Typescript ?

### ISSUE THREAD

**Issue by lyquocphong** [seppevs/migrate-mongo#79]
I want to use migrate-mongo with nestjs and that use typescript and I would like to ask does it work with ts. Another thing is can I use mongo model in migration

**Comment by seppevs** [comment]
Sorry, I have no plans to integrate Typescript in migrate-mongo.

**Comment by beaulac** [comment]
Got this to work with very little changes using [ts-node](https://github.com/TypeStrong/ts-node)

```ts
// migrate-mongo-config.ts

export = {
    migrationFileExtension: '.ts',
    // ... rest of your config as usual
};
```

```ts
// migrations/202009091234-example-migration.ts

import { Db } from 'mongodb';

export = {
  up(db: Db) {
    return db
      .collection('foo')
      .updateMany({}, { $set: { bar: 'baz' } });
  },

  down(db: Db) {
    return db
      .collection('foo')
      .updateMany({}, { $unset: { bar: '' } });
  },
};
```

In package.json:
```json
{
  "scripts": {
    "migrate:create": "sh -c 'ts-node --script-mode node_modules/.bin/migrate-mongo create $0 -f migrate-mongo-config.ts' ",
    "migrate:status": "ts-node --script-mode node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts",
    "migrate:undo-last": "ts-node --script-mode node_modules/.bin/migrate-mongo down -f migrate-mongo-config.ts && npm run migrate:status",
    "migrate": "ts-node --script-mode node_modules/.bin/migrate-mongo up -f migrate-mongo-config.ts"
  },
  "devDependencies": {
    "ts-node": ">=8",
    "migrate-mongo": "^8.1.1"
}
```

The command boilerplate is a little tedious but it's not something that comes up much after setting it up.
Seems to work without issues :)

**Comment by dbads** [comment]
> Got this to work with very little changes using [ts-node](https://github.com/TypeStrong/ts-node)
> 
> ```ts
> // migrate-mongo-config.ts
> 
> export = {
>     migrationFileExtension: '.ts',
>     // ... rest of your config as usual
> };
> ```
> 
> ```ts
> // migrations/202009091234-example-migration.ts
> 
> import { Db } from 'mongodb';
> 
> export = {
>   up(db: Db) {
>     return db
>       .collection('foo')
>       .updateMany({}, { $set: { bar: 'baz' } });
>   },
> 
>   down(db: Db) {
>     return db
>       .collection('foo')
>       .updateMany({}, { $unset: { bar: '' } });
>   },
> };
> ```
> 
> In package.json:
> 
> ```json
> {
>   "scripts": {
>     "migrate:create": "sh -c 'ts-node node_modules/.bin/migrate-mongo create $0 -f migrate-mongo-config.ts' ",
>     "migrate:status": "ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts",
>     "migrate:undo-last": "ts-node node_modules/.bin/migrate-mongo down -f migrate-mongo-config.ts && npm run migrate:status",
>     "migrate": "ts-node node_modules/.bin/migrate-mongo up -f migrate-mongo-config.ts"
>   },
>   "devDependencies": {
>     "ts-node": ">=8",
>     "migrate-mongo": "^8.1.1"
> }
> ```
> 
> The command boilerplate is a little tedious but it's not something that comes up much after setting it up.
> Seems to work without issues :)

Using this, facing issue with global types not being recognized?

**Comment by dbads** [comment]
Hey @beaulac I am trying the way you suggested it seems to work unless there comes some path which uses global types.
global types not being recognized?

**Comment by beaulac** [comment]
@dbads I'm not sure I understand the specific issue, but hopefully these help you find a solution:

If you're depending on ambient declarations in your source files, note that `ts-node` doesn't load all source files; it only interprets the dependency chain from the entry point (in this case the main `migrate-mongo` script and the migration files themselves): https://github.com/TypeStrong/ts-node#help-my-types-are-missing

If you're already using `types` or `typeRoots` in your `tsconfig.json`, maybe `ts-node` is not able to find your config, you would need to specify it: https://github.com/TypeStrong/ts-node#loading-tsconfigjson

**Comment by dbads** [comment]
@beaulac Okay, I get it. Thank you.

**Comment by voronin-de** [comment]
@beaulac I also have tried your approach, but I am getting a weird message:
```bash
user@LTNUE010 MINGW64 /c/workspaces/profiler (feature/migtests)
$ npm run migrate:status

> profiler@0.0.0 migrate:status C:\workspaces\profiler
> ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts

C:\workspaces\profiler\node_modules\.bin\migrate-mongo:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main (C:\workspaces\profiler\node_modules\ts-node\src\bin.ts:198:14)
    at Object.<anonymous> (C:\workspaces\profiler\node_modules\ts-node\src\bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! profiler@0.0.0 migrate:status: `ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the profiler@0.0.0 migrate:status script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-05-15T20_16_36_323Z-debug.log
```

I configured `migrate:status` in `scripts` section of my `package.json` as follows: `"migrate:status": "ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts"`.

I am using `migrate-mongo` version `8.2.2`.

Tests I have written for my migration scripts work well. Of course my migration scripts as well as the corresponding tests are written in TypeScript.

I had to change the script layout a little:
```ts
import { Db } from 'mongodb';
import { Profile } from './profile';

export async function up(db: Db) {
  // regex for discovering the absence of a leading dataUrl of the image-attribute
  const dataUrlNotPresent: RegExp = new RegExp('^(?!data:image.{1}.{2,4};base64,).*');

  // collect all profiles not containing a leading dataUrl
  const profiles: Profile[] = await db
    .collection<Profile>('profiles')
    .find({ image: { $regex: dataUrlNotPresent } })
    .toArray();
  console.log('Migrating %d profile(s) up...', profiles.length);

  // prefix the image-attribute of each profile within the profiles array
  // note: the image data is assumed to be a Base64-encoded JPEG file
  const operations: Promise<void>[] = profiles.map(async (profile: Profile) => {
    await db
      .collection('profiles')
      .updateOne({ _id: profile._id }, { $set: { image: 'data:image/jpeg;base64,' + profile.image } });
  });
  return Promise.all(operations);
}

export async function down(db: Db) {
  // regex for discovering the presence of a dataUrl in the image-attribute
  const dataUrlPresent = /data:image.{1}.{2,4};base64,.*/;

  // collect all profiles containing a leading dataUrl
  const profiles: Profile[] = await db
    .collection<Profile>('profiles')
    .find({ image: { $regex: dataUrlPresent } })
    .toArray();
  console.log('Migrating %d profile(s) down...', profiles.length);

  // remove the leading dataUrl prefix from the image-attribute of each profile within the profiles array
  // note: format-related information is lost; if the migration is upped again, PNG-data might get prefixed with a JPEG dataUrl
  const operations: Promise<void>[] = profiles.map(async (profile: Profile) => {
    await db
      .collection('profiles')
      .updateOne({ _id: profile._id }, { $set: { image: profile.image.substring(profile.image.indexOf(',') + 1) } });
  });
  return Promise.all(operations);
}
```
This does not seem to be the reason it's failing though, is it?

**Comment by MarceloBD** [comment]
I changed to 

> 
> 
> @beaulac I also have tried your approach, but I am getting a weird message:
> 
> ```shell
> user@LTNUE010 MINGW64 /c/workspaces/profiler (feature/migtests)
> $ npm run migrate:status
> 
> > profiler@0.0.0 migrate:status C:\workspaces\profiler
> > ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts
> 
> C:\workspaces\profiler\node_modules\.bin\migrate-mongo:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> 
> SyntaxError: missing ) after argument list
>     at wrapSafe (internal/modules/cjs/loader.js:979:16)
>     at Module._compile (internal/modules/cjs/loader.js:1027:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at main (C:\workspaces\profiler\node_modules\ts-node\src\bin.ts:198:14)
>     at Object.<anonymous> (C:\workspaces\profiler\node_modules\ts-node\src\bin.ts:288:3)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! profiler@0.0.0 migrate:status: `ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the profiler@0.0.0 migrate:status script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-05-15T20_16_36_323Z-debug.log
> ```
> 
> I configured `migrate:status` in `scripts` section of my `package.json` as follows: `"migrate:status": "ts-node node_modules/.bin/migrate-mongo status -f migrate-mongo-config.ts"`.
> 
> I am using `migrate-mongo` version `8.2.2`.
> 
> Tests I have written for my migration scripts work well. Of course my migration scripts as well as the corresponding tests are written in TypeScript.
> 
> I had to change the script layout a little:
> 
> ```ts
> import { Db } from 'mongodb';
> import { Profile } from './profile';
> 
> export async function up(db: Db) {
>   // regex for discovering the absence of a leading dataUrl of the image-attribute
>   const dataUrlNotPresent: RegExp = new RegExp('^(?!data:image.{1}.{2,4};base64,).*');
> 
>   // collect all profiles not containing a leading dataUrl
>   const profiles: Profile[] = await db
>     .collection<Profile>('profiles')
>     .find({ image: { $regex: dataUrlNotPresent } })
>     .toArray();
>   console.log('Migrating %d profile(s) up...', profiles.length);
> 
>   // prefix the image-attribute of each profile within the profiles array
>   // note: the image data is assumed to be a Base64-encoded JPEG file
>   const operations: Promise<void>[] = profiles.map(async (profile: Profile) => {
>     await db
>       .collection('profiles')
>       .updateOne({ _id: profile._id }, { $set: { image: 'data:image/jpeg;base64,' + profile.image } });
>   });
>   return Promise.all(operations);
> }
> 
> export async function down(db: Db) {
>   // regex for discovering the presence of a dataUrl in the image-attribute
>   const dataUrlPresent = /data:image.{1}.{2,4};base64,.*/;
> 
>   // collect all profiles containing a leading dataUrl
>   const profiles: Profile[] = await db
>     .collection<Profile>('profiles')
>     .find({ image: { $regex: dataUrlPresent } })
>     .toArray();
>   console.log('Migrating %d profile(s) down...', profiles.length);
> 
>   // remove the leading dataUrl prefix from the image-attribute of each profile within the profiles array
>   // note: format-related information is lost; if the migration is upped again, PNG-data might get prefixed with a JPEG dataUrl
>   const operations: Promise<void>[] = profiles.map(async (profile: Profile) => {
>     await db
>       .collection('profiles')
>       .updateOne({ _id: profile._id }, { $set: { image: profile.image.substring(profile.image.indexOf(',') + 1) } });
>   });
>   return Promise.all(operations);
> }
> ```
> 
> This does not seem to be the reason it's failing though, is it?

I changed to node_modules/migrate-mongo/bin/migrate-mongo instead of .bin. I think the other way didn't work on windows. Also, it can also be runned with babel-node 

"migrate": "babel-node --extensions \".ts\" -- node_modules/migrate-mongo/bin/migrate-mongo up -f migrate-mongo-config.ts"

**Comment by alisherafat01** [comment]
this is my migrate-config.ts
```
import * as dotenv from 'dotenv';
dotenv.config();

export = {
  mongodb: {
    // TODO Change (or review) the url to your MongoDB:
    url: process.env.MONGO_CONNECTION,

    options: {
      //useNewUrlParser: true // removes a deprecation warning when connecting
      //   connectTimeoutMS: 3600000, // increase connection timeout to 1 hour
      //   socketTimeoutMS: 3600000, // increase socket timeout to 1 hour
    },
  },

  // The migrations dir, can be an relative or absolute path. Only edit this when really necessary.
  migrationsDir: './src/storage/mongodb/migrations',

  // The mongodb collection where the applied changes are stored. Only edit this when really necessary.
  changelogCollectionName: 'migrations',

  // The file extension to create migrations and search for in migration dir
  migrationFileExtension: '.ts',

  // Enable the algorithm to create a checksum of the file contents and use that in the comparison to determin
  // if the file should be run.  Requires that scripts are coded to be run multiple times.
  useFileHash: false,
};

```

**Comment by bvpranu97** [comment]
Change the .js extension to .ts extension. Then use the below template.
```
import * as mongo from "mongodb";
export = {
  async up(db: mongo.Db, client: mongo.MongoClient) {
    //Migrate up Logic
  },

  async down(db: mongo.Db, client: mongo.MongoClient) {
  //Migrate down Logic
  },
};
```
Make sure you install mongodb using `npm install mongodb`

Inorder to complile and run the migration use tsc command. 

Don't forget to change  `migrationsDir` to the compiled migration directory.

**Comment by FossPrime** [comment]
Someone forked this project with a decent typescript implementation

https://github.com/mycodeself/mongo-migrate-ts

It's inherently much more self documented, easier to maintain and easier to use.
